# Generated by Django 3.2.7 on 2022-07-12 02:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Greenhouse_Database_Connection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=300)),
                ('ip', models.CharField(max_length=30)),
                ('database_name', models.CharField(max_length=100)),
                ('table_name', models.CharField(max_length=100)),
                ('user', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('greenhouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.greenhouse')),
            ],
        ),
        migrations.CreateModel(
            name='Crop_Limits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_limit', models.CharField(max_length=20)),
                ('min_limit', models.CharField(max_length=20)),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.crop')),
                ('phys_vars', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.physical_variable')),
            ],
        ),
    ]
