# Generated by Django 3.2.7 on 2022-07-14 00:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_crop_limits_greenhouse_database_connection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crop_limits',
            name='crop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.crop', unique=True),
        ),
        migrations.AlterField(
            model_name='crop_limits',
            name='phys_vars',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.physical_variable', unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='crop_limits',
            unique_together={('crop', 'phys_vars')},
        ),
    ]
