# Generated by Django 3.2.7 on 2022-07-14 22:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20220713_1855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crop_limits',
            name='crop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.crop'),
        ),
        migrations.AlterField(
            model_name='crop_limits',
            name='phys_vars',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.physical_variable'),
        ),
    ]
